language: python
python:
  - "3.6"

sudo: required

services:
  - docker

install:
  - pip install coveralls

script:
  - coverage run --source=scrapemeagain setup.py test

after_success:
  - coveralls

notifications:
  email: false
